# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        python-version: ["3.7", "3.8", "3.9", "3.10.0", "3.11.2"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Lint with flake8
      run: |
        python labfile.py brew --progress=none lint
    - name: Test with pytest and generate coverage
      run: |
        python labfile.py brew --progress=none coverage
    - name: Type check with mypy
      run: |
        python labfile.py brew --progress=none type_check
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        verbose: true
